[RUN-1515] Tidy up docker image
snyk/kubernetes-monitor pull request #763
Opened 2021-05-18 15:03 UTC by kat1906

Exclude files which are not needed from Docker by adding to .dockerignore.

- [ ] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [ ] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [x] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does

Tidies up the Docker image by excluding files which are not needed by adding to .dockerignore.

2021-05-18 15:30 UTC, jmickey approved these changes

2021-05-18 16:12 UTC, ivanstanev requested changes
Could we make this a `feat` or `fix` so that it can release a new image with these changes?

2021-05-18 17:45 UTC, ivanstanev approved these changes

2021-05-19 07:29 UTC, merged

2021-05-21 08:00 UTC, snyksec commented
:tada: This PR is included in version 1.55.1 :tada:

The release is available on [GitHub release](https://github.com/snyk/kubernetes-monitor/releases/tag/v1.55.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: