[RUN-1559] Rename workload-auto-import policy to workload-events
snyk/kubernetes-monitor pull request #771
Opened 2021-05-26 17:00 UTC by kat1906

- [x] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [ ] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [x] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does

Rename workload-auto-import policy to workload-events

2021-05-26 17:02 UTC, jmickey approved these changes

2021-05-26 17:22 UTC, ivanstanev requested changes
Nice! Could we also rename any references to "auto import" like `constructWorkloadAutoImportPolicy()` can become `constructWorkloadPolicy()` and `sendWorkloadAutoImportPolicy()` can become `sendWorkloadPolicy()`?

2021-05-27 09:57 UTC, ivanstanev approved these changes

2021-05-27 10:53 UTC, merged

2021-05-27 11:08 UTC, snyksec commented
:tada: This PR is included in version 1.58.2 :tada:

The release is available on [GitHub release](https://github.com/snyk/kubernetes-monitor/releases/tag/v1.58.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: